[package]
name = "attestations"
version = "0.1.0"
edition = "2023_11"

[dependencies]
starknet = "2.6.3"

[dev-dependencies]
cairo_test = "2.11.4"

[[target.starknet-contract]]

[tool.snforge]
# Directory containing Cairo source files
src = "src"
